version: '3'

services:

  web:
   build: ./ssl
   ports:
    - 80:80
    - 443:443
   volumes:
    - ./ssl/certs:/etc/nginx/certs
   depends_on:
    - node
  node: 
   build: ./AuthenticationApi/01-login
   volumes:
    - ./AuthenticationApi/01-login:/app